/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import utils.ThermalPrinter;
import entity.*;
import dao.*;
import java.util.List;

/**
 * Dialog chọn in sau khi thanh toán
 * @author PC
 */
public class Dialog_In extends javax.swing.JDialog {

    private String maHoaDon;
    private int luaChon = -1; // 0: In hóa đơn, 1: In vé, 2: In cả hai, 3: Không in
    
    /**
     * Creates new form Dialog_In
     */
    public Dialog_In(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    /**
     * Constructor với mã hóa đơn
     */
    public Dialog_In(java.awt.Frame parent, boolean modal, String maHoaDon) {
        super(parent, modal);
        this.maHoaDon = maHoaDon;
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    /**
     * Lấy lựa chọn của người dùng
     */
    public int getLuaChon() {
        return luaChon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Thanh toán thành công");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/check.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ==================== METHODS IN ẤN ====================
    
    /**
     * Tự động in hóa đơn và vé (gọi sau khi thanh toán thành công)
     */
    public void autoInHoaDonVaVe() {
        if (maHoaDon == null || maHoaDon.isEmpty()) {
            System.err.println("❌ Không có mã hóa đơn để in!");
            return;
        }
        
        // Chạy trong background thread để không block UI
        new Thread(() -> {
            try {
                System.out.println("🚀 Bắt đầu tự động in hóa đơn và vé...");
                
                // Bước 1: In hóa đơn trước
                System.out.println("📋 Bước 1: In hóa đơn...");
                inHoaDon(maHoaDon);
                
                // Đợi 2 giây trước khi in vé
                System.out.println("⏳ Đợi 2 giây trước khi in vé...");
                Thread.sleep(2000);
                
                // Bước 2: In tất cả vé (mỗi vé cách nhau 2s)
                System.out.println("🎫 Bước 2: In tất cả vé...");
                inVe(maHoaDon);
                
                System.out.println("✅ Hoàn thành tự động in hóa đơn và vé!");
                
            } catch (Exception e) {
                System.err.println("❌ Lỗi khi tự động in: " + e.getMessage());
                e.printStackTrace();
            }
        }).start();
    }
    
    /**
     * In hóa đơn
     */
    private void inHoaDon(String maHoaDon) {
        try {
            System.out.println("🖨️ In hóa đơn: " + maHoaDon);
            
            // Load hóa đơn từ database
            HoaDon_DAO hoaDonDAO = new HoaDon_DAO();
            HoaDon hoaDon = hoaDonDAO.findByMaHoaDon(maHoaDon);
            
            if (hoaDon == null) {
                System.err.println("❌ Không tìm thấy hóa đơn: " + maHoaDon);
                return;
            }
            
            // Load chi tiết hóa đơn và vé
            ChiTietHoaDon_DAO chiTietHoaDonDAO = new ChiTietHoaDon_DAO();
            Ve_DAO veDAO = new Ve_DAO();
            List<ChiTietHoaDon> chiTietList = chiTietHoaDonDAO.findByMaHoaDon(maHoaDon);
            
            // Load thông tin vé cho mỗi chi tiết
            for (ChiTietHoaDon cthd : chiTietList) {
                Ve ve = veDAO.findByMaVe(cthd.getMaVe());
                cthd.setVe(ve);
            }
            
            // Set danh sách chi tiết vào hóa đơn
            hoaDon.setDanhSachChiTiet(chiTietList);
            
            // In hóa đơn (chế độ tự động)
            ThermalPrinter printer = new ThermalPrinter(hoaDon, chiTietList);
            printer.setAutoPrint(true); // ⚡ Đánh dấu là in tự động sau bán
            boolean success = printer.printInvoice();
            
            if (!success) {
                System.err.println("❌ Lỗi khi in hóa đơn!");
            } else {
                System.out.println("✅ In hóa đơn thành công!");
            }
        } catch (Exception e) {
            System.err.println("❌ Lỗi khi in hóa đơn: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * In từng vé (mỗi vé cách nhau 2 giây)
     */
    private void inVe(String maHoaDon) {
        try {
            System.out.println("🖨️ In vé từ hóa đơn: " + maHoaDon);
            
            // Load danh sách vé từ hóa đơn
            Ve_DAO veDAO = new Ve_DAO();
            List<Ve> danhSachVe = veDAO.findByMaHoaDon(maHoaDon);
            
            if (danhSachVe == null || danhSachVe.isEmpty()) {
                System.err.println("❌ Không tìm thấy vé nào cho hóa đơn: " + maHoaDon);
                return;
            }
            
            System.out.println("📄 Bắt đầu in " + danhSachVe.size() + " vé...");
            
            // In từng vé, mỗi vé cách nhau 2 giây
            for (int i = 0; i < danhSachVe.size(); i++) {
                Ve ve = danhSachVe.get(i);
                
                System.out.println("🖨️ In vé " + (i + 1) + "/" + danhSachVe.size() + ": " + ve.getMaVe());
                boolean success = ThermalPrinter.printTicket(ve, true); // ⚡ Chế độ in tự động
                
                if (!success) {
                    System.err.println("❌ Lỗi khi in vé: " + ve.getMaVe());
                } else {
                    System.out.println("✅ In vé thành công: " + ve.getMaVe());
                }
                
                // Đợi 2 giây trước khi in vé tiếp theo (trừ vé cuối cùng)
                if (i < danhSachVe.size() - 1) {
                    Thread.sleep(2000);
                }
            }
            
            System.out.println("✅ Hoàn thành in tất cả vé!");
        } catch (Exception e) {
            System.err.println("❌ Lỗi khi in vé: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_In dialog = new Dialog_In(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
