/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import entity.*;
import dao.*;
import utils.SessionManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author PC
 */
public class Dialog_QR extends JDialog {

    // ========== BIẾN INSTANCE ==========
    private boolean isNhapLai = false;
    private boolean isThanhToanThanhCong = false;
    private boolean isTreoDon = false;
    
    private Gui_NhapThongTinBanVe previousGui;
    private DonTreoDat donTreo;
    
    private String cccd;
    private String hoTen;
    private String sdt;
    private String email;
    private int soLuongVe;
    private double tongTien;
    private double khuyenMai; // Đã đổi từ String sang double
    
    private JTextField txtTienKhachDua;
    private NumberFormat currencyFormat;
    
    // ========== CONSTRUCTORS ==========
    
    /**
     * Creates new form Dialog_QR
     */
    public Dialog_QR(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        currencyFormat = NumberFormat.getInstance(Locale.forLanguageTag("vi-VN"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        lblTien = new JLabel();
        jLabel4 = new JLabel();
        jLabel7 = new JLabel();
        jLabel9 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel8 = new JLabel();
        btnQuayLai = new JButton();
        btnTreoDon = new JButton();
        btnThanhToan = new JButton();
        jLabel11 = new JLabel();
        jLabel10 = new JLabel();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        pnlQR = new JPanel();
        jLabel16 = new JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/icon/qr1.png"))); // NOI18N

        jLabel2.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Thanh toán chuyển khoản");

        lblTien.setFont(new Font("Segoe UI", 1, 20)); // NOI18N
        lblTien.setHorizontalAlignment(SwingConstants.CENTER);
        lblTien.setText("200.000 VND");

        jLabel4.setText("Chủ tài khoản:");

        jLabel7.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("CÔNG TY CỔ PHẦN VẬN TẢI ĐƯỜNG SẮT HKTA");

        jLabel9.setText("Ngân hàng:");

        jLabel5.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("MBBank");

        jLabel6.setText("Số tài khoản:");

        jLabel8.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("0766609129");

        btnQuayLai.setIcon(new ImageIcon(getClass().getResource("/icon/arrow.png"))); // NOI18N
        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnTreoDon.setIcon(new ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        btnTreoDon.setText("Treo đơn");
        btnTreoDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreoDonActionPerformed(evt);
            }
        });

        btnThanhToan.setIcon(new ImageIcon(getClass().getResource("/icon/payment.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán ");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel11.setText("Mã hóa đơn: ");

        jLabel10.setText("CCCD:");

        jLabel12.setText("Số điện thoại:");

        jLabel13.setText("Họ tên:");

        jLabel14.setText("Số lượng vé:");

        GroupLayout pnlQRLayout = new GroupLayout(pnlQR);
        pnlQR.setLayout(pnlQRLayout);
        pnlQRLayout.setHorizontalGroup(
            pnlQRLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        pnlQRLayout.setVerticalGroup(
            pnlQRLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jLabel16.setText("Khuyến mãi:");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnQuayLai)
                                .addGap(58, 58, 58)
                                .addComponent(btnTreoDon)
                                .addGap(55, 55, 55)
                                .addComponent(btnThanhToan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlQR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTien, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTien)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(51, 51, 51))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlQR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuayLai, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTreoDon, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // Quay lại Gui_NhapThongTinBanVe (giữ nguyên dữ liệu đã nhập)
        isNhapLai = true;
        isThanhToanThanhCong = false;
        isTreoDon = false;
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnTreoDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreoDonActionPerformed
        // ⚡ VALIDATE "ĐỐI TƯỢNG" TRƯỚC KHI TREO ĐƠN
        if (previousGui != null) {
            javax.swing.table.TableModel model = previousGui.getModelThongTinVe();
            for (int i = 0; i < model.getRowCount(); i++) {
                String doiTuong = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString().trim() : "";
                if (doiTuong.isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                        "Vui lòng chọn Đối tượng cho vé ở dòng " + (i + 1) + " trước khi treo đơn!",
                        "Thiếu thông tin",
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }

        // Lưu đơn treo
        DonTreoDat donTreo = new DonTreoDat();
        donTreo.setCccdNguoiDat(cccd);
        donTreo.setHoTenNguoiDat(hoTen);
        donTreo.setSdtNguoiDat(sdt);
        donTreo.setEmailNguoiDat(email);
        donTreo.setSoLuongVe(soLuongVe);
        donTreo.setTongTien(tongTien);

        // ⚡ Lưu thông tin ga đi, ga đến và LichTrinh
        if (previousGui != null) {
            try {
                LichTrinh lt = previousGui.getPreviousGuiBanVe().getLichTrinhDangChon();
                if (lt != null) {
                    String gaDi = lt.getGaDi() != null ? lt.getGaDi().getTenGa() : "";
                    String gaDen = lt.getGaDen() != null ? lt.getGaDen().getTenGa() : "";
                    donTreo.setGaDi(gaDi);
                    donTreo.setGaDen(gaDen);

                    // ⚡ LƯU LICH TRINH (quan trọng để lưu vé vào database)
                    donTreo.setLichTrinh(lt);
                }
            } catch (Exception e) {
                System.out.println("Không lấy được thông tin ga: " + e.getMessage());
            }
        }

        // Lấy thông tin vé từ Gui_NhapThongTinBanVe
        if (previousGui != null) {
            // Lấy dữ liệu từ bảng vé
            javax.swing.table.TableModel model = previousGui.getModelThongTinVe();

            // ⚡ LẤY TỪ GUI_NHAPTHONGTINBANVE (không phải từ Gui_BanVe vì đã bị clear)
            List<ChoNgoi> danhSachChoNgoi = previousGui.getDanhSachChoNgoi();

            // ⚡ Lấy danh sách lịch trình (quan trọng cho khứ hồi)
            List<LichTrinh> danhSachLichTrinh = previousGui.getDanhSachLichTrinh();
            List<entity.Ga> danhSachGaDi = previousGui.getDanhSachGaDi();
            List<entity.Ga> danhSachGaDen = previousGui.getDanhSachGaDen();
            
            System.out.println("🟡 DEBUG TREO ĐƠN: Số vé trong table = " + model.getRowCount());
            System.out.println("🟡 DEBUG TREO ĐƠN: Số ghế (ChoNgoi) = " + (danhSachChoNgoi != null ? danhSachChoNgoi.size() : "null"));
            System.out.println("🟡 DEBUG TREO ĐƠN: Số lịch trình = " + (danhSachLichTrinh != null ? danhSachLichTrinh.size() : "null"));

            for (int i = 0; i < model.getRowCount(); i++) {
                DonTreoDat.ThongTinVeTam veTam = new DonTreoDat.ThongTinVeTam();

                Object soGiayTo = model.getValueAt(i, 0);
                Object hoTenVe = model.getValueAt(i, 1);
                Object doiTuong = model.getValueAt(i, 2);
                Object thongTinCho = model.getValueAt(i, 3);
                Object giaVe = model.getValueAt(i, 4);
                Object giamGia = model.getValueAt(i, 5);
                Object thanhTien = model.getValueAt(i, 6);

                veTam.setSoGiayTo(soGiayTo != null ? soGiayTo.toString() : "");
                veTam.setHoTen(hoTenVe != null ? hoTenVe.toString() : "");
                veTam.setDoiTuong(doiTuong != null ? doiTuong.toString() : "");
                veTam.setThongTinCho(thongTinCho != null ? thongTinCho.toString() : "");

                // ⚡ LƯU THÔNG TIN GHẾ (để khi thanh toán có thể lưu vào database)
                if (danhSachChoNgoi != null && i < danhSachChoNgoi.size()) {
                    veTam.setChoNgoi(danhSachChoNgoi.get(i));
                    System.out.println("🟡 Vé #" + i + ": ChoNgoi = " + danhSachChoNgoi.get(i).getMaChoNgoi());
                } else {
                    System.out.println("❌ Vé #" + i + ": KHÔNG CÓ ChoNgoi!");
                }

                // ⚡ LƯU LỊCH TRÌNH CHO TỪNG VÉ (quan trọng với khứ hồi)
                if (danhSachLichTrinh != null && i < danhSachLichTrinh.size()) {
                    veTam.setLichTrinh(danhSachLichTrinh.get(i));
                    System.out.println("🟡 Vé #" + i + ": LichTrinh = " + danhSachLichTrinh.get(i).getMaLichTrinh());
                } else {
                    System.out.println("❌ Vé #" + i + ": KHÔNG CÓ LichTrinh!");
                }
                
                // ⚡ LƯU GA ĐI / GA ĐẾN CHO TỪNG VÉ (Quan trọng cho quản lý chặng)
                if (danhSachGaDi != null && i < danhSachGaDi.size()) {
                    veTam.setGaDi(danhSachGaDi.get(i));
                }
                if (danhSachGaDen != null && i < danhSachGaDen.size()) {
                    veTam.setGaDen(danhSachGaDen.get(i));
                }

                try {
                    veTam.setGiaVe(giaVe != null ? Double.parseDouble(giaVe.toString()) : 0);
                    veTam.setGiamGia(giamGia != null ? Double.parseDouble(giamGia.toString()) : 0);
                    veTam.setThanhTien(thanhTien != null ? Double.parseDouble(thanhTien.toString()) : 0);
                } catch (Exception e) {
                    veTam.setGiaVe(0);
                    veTam.setGiamGia(0);
                    veTam.setThanhTien(0);
                }

                donTreo.themVe(veTam);
            }
        }

        // ⚠️ QUAN TRỌNG: Thêm đơn treo VÀO DANH SÁCH TRƯỚC để tạo maDonTreo
        QuanLyDonTreo.themDonTreo(donTreo);

        // SAU ĐÓ mới lưu ghế vào danh sách giữ chỗ (với maDonTreo đã được set)
        // ⚡ Lưu ghế với maLichTrinh để hỗ trợ khứ hồi
        if (previousGui != null) {
            System.out.println("🟡 ============ BẮT ĐẦU TREO ĐƠN ============");
            for (DonTreoDat.ThongTinVeTam veTam : donTreo.getDanhSachVe()) {
                if (veTam.getChoNgoi() != null) {
                    String maChoNgoi = veTam.getChoNgoi().getMaChoNgoi();
                    String maLichTrinh = veTam.getLichTrinh() != null ? veTam.getLichTrinh().getMaLichTrinh() : null;
                    String maGaDi = veTam.getGaDi() != null ? veTam.getGaDi().getMaGa() : null;
                    String maGaDen = veTam.getGaDen() != null ? veTam.getGaDen().getMaGa() : null;
                    
                    System.out.println("🟡 TREO GHẾ: " + maChoNgoi + " | Lịch trình: " + maLichTrinh + " | Chặng: " + maGaDi + "-" + maGaDen);
                    QuanLyGheGiuCho.themGheGiuCho(maChoNgoi, donTreo.getMaDonTreo(), maLichTrinh, maGaDi, maGaDen);
                }
            }
            System.out.println("🟡 ============ KẾT THÚC TREO ĐƠN ============");
        }

        isTreoDon = true;
        isThanhToanThanhCong = false;
        isNhapLai = false;

        // ⚡ RELOAD SƠ ĐỒ GHẾ SAU KHI TREO ĐƠN để hiển thị ghế màu vàng
        Gui_BanVe guiBanVeToReload = null;
        try {
            if (previousGui != null && previousGui.getPreviousGuiBanVe() != null) {
                guiBanVeToReload = previousGui.getPreviousGuiBanVe();
            }
        } catch (Exception e) {
            System.err.println("Không tìm thấy Gui_BanVe: " + e.getMessage());
        }

        final Gui_BanVe finalGuiBanVe = guiBanVeToReload;
        if (finalGuiBanVe != null) {
            SwingUtilities.invokeLater(() -> {
                System.out.println("🟡 Đang reload sơ đồ ghế sau khi TREO ĐƠN...");
                finalGuiBanVe.reloadSoDoGhe();
                System.out.println("✅ Đã reload sơ đồ ghế - ghế giữ chỗ hiển thị màu vàng!");
            });
        }

        dispose();
    }//GEN-LAST:event_btnTreoDonActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // Validate dữ liệu
        String tienKhachDuaText = txtTienKhachDua.getText().trim();

        if (tienKhachDuaText.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Vui lòng nhập số tiền khách đưa!",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
            txtTienKhachDua.requestFocus();
            return;
        }

        try {
            // Xóa dấu phân cách
            tienKhachDuaText = tienKhachDuaText.replaceAll("[,.]", "");
            double tienKhachDua = Double.parseDouble(tienKhachDuaText);
            double tongThanhToan = tongTien - khuyenMai;

            if (tienKhachDua < tongThanhToan) {
                JOptionPane.showMessageDialog(this,
                    "Số tiền khách đưa không đủ!\n" +
                    "Cần thanh toán: " + currencyFormat.format(tongThanhToan) + " ₫\n" +
                    "Khách đưa: " + currencyFormat.format(tienKhachDua) + " ₫\n" +
                    "Thiếu: " + currencyFormat.format(tongThanhToan - tienKhachDua) + " ₫",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ⚡ VALIDATE "ĐỐI TƯỢNG" - Kiểm tra tất cả vé đã chọn đối tượng
            if (previousGui != null) {
                javax.swing.table.TableModel model = previousGui.getModelThongTinVe();
                for (int i = 0; i < model.getRowCount(); i++) {
                    String doiTuong = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString().trim() : "";
                    if (doiTuong.isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                            "Vui lòng chọn Đối tượng cho vé ở dòng " + (i + 1) + "!",
                            "Thiếu thông tin",
                            JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
            }

            // ============ LƯU VÀO DATABASE ============
            String maHoaDon = "HD" + System.currentTimeMillis();
            boolean luuThanhCong = luuVaoDatabase(maHoaDon, cccd, hoTen, sdt, email, soLuongVe, tongTien, khuyenMai);

            if (!luuThanhCong) {
                JOptionPane.showMessageDialog(this,
                    "Lỗi lưu dữ liệu vào database!\nVui lòng thử lại.",
                    "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            isThanhToanThanhCong = true;
            isNhapLai = false;
            isTreoDon = false;

            // Lưu parentFrame trước khi dispose
            Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);

            // Đóng dialog thanh toán
            dispose();

            // ⚡ MỞ DIALOG IN và tự động in hóa đơn + vé
            Dialog_In dialogIn = new Dialog_In(parentFrame, false, maHoaDon); // false = non-modal để có thể in background
            dialogIn.setVisible(true);
            
            // ⚡ Tự động in hóa đơn và vé (hóa đơn trước, sau đó vé cách nhau 2s)
            dialogIn.autoInHoaDonVaVe();

            // ⚡ RELOAD sơ đồ ghế để cập nhật ghế đã bán (màu đỏ)
            Gui_BanVe guiBanVeToReload = null;

            if (previousGui != null) {
                // Trường hợp bán vé thường
                guiBanVeToReload = previousGui.getPreviousGuiBanVe();
                if (guiBanVeToReload != null) {
                    // ⚡ KHÔNG gọi xoaTatCaGheDaChon() ở đây vì nó có reload bên trong
                    // Sẽ gọi reloadSoDoGhe() sau để đảm bảo database đã commit
                    // reloadSoDoGhe() sẽ tự động clear danh sách ghế và giỏ vé

                    // Quay về Gui_BanVe
                    gui.menu.form.MainForm mainForm =
                    (gui.menu.form.MainForm) SwingUtilities.getAncestorOfClass(
                        gui.menu.form.MainForm.class, previousGui);

                    if (mainForm != null) {
                        mainForm.showForm(guiBanVeToReload);
                    }
                }
            } else if (donTreo != null) {
                // ⚡ Trường hợp xử lý đơn tạm → Tìm Gui_BanVe để reload
                System.out.println("🔵 Xử lý đơn treo - Tìm Gui_BanVe để reload...");
                try {
                    // Tìm MainForm
                    gui.menu.form.MainForm mainForm = null;
                    for (Window window : Window.getWindows()) {
                        if (window instanceof JFrame) {
                            JFrame frame = (JFrame) window;
                            Component comp = frame.getContentPane().getComponent(0);
                            if (comp instanceof gui.menu.form.MainForm) {
                                mainForm = (gui.menu.form.MainForm) comp;
                                break;
                            }
                        }
                    }

                    if (mainForm != null) {
                        guiBanVeToReload = findGuiBanVeInMainForm(mainForm);
                        if (guiBanVeToReload != null) {
                            System.out.println("✅ Tìm thấy Gui_BanVe!");
                        } else {
                            System.out.println("⚠️ Không tìm thấy Gui_BanVe trong MainForm");
                        }
                    } else {
                        System.out.println("⚠️ Không tìm thấy MainForm");
                    }
                } catch (Exception e) {
                    System.err.println("❌ Lỗi khi tìm Gui_BanVe: " + e.getMessage());
                    e.printStackTrace();
                }
            }

            // Reload sơ đồ ghế SAU KHI lưu database
            // ⚡ Sử dụng invokeLater để đảm bảo reload sau khi database đã commit
            final Gui_BanVe finalGuiBanVeToReload = guiBanVeToReload;
            final boolean isFromDonTreo = (donTreo != null);

            if (finalGuiBanVeToReload != null) {
                SwingUtilities.invokeLater(() -> {
                    System.out.println("🔄 Đang reload sơ đồ ghế sau khi thanh toán...");
                    LichTrinh ltHienTai = finalGuiBanVeToReload.getLichTrinhDangChon();
                    if (ltHienTai != null) {
                        System.out.println("📍 Lịch trình đang hiển thị: " + ltHienTai.getMaLichTrinh());
                    }
                    finalGuiBanVeToReload.reloadSoDoGhe();
                    System.out.println("✅ Đã reload sơ đồ ghế!");
                    System.out.println("💡 LƯU Ý: Nếu đơn khứ hồi, chuyển sang chiều kia sẽ tự động hiển thị màu đỏ khi query database!");
                });
            } else if (isFromDonTreo) {
                // ⚠️ Không tìm thấy Gui_BanVe → Thông báo cho user
                System.out.println("⚠️ Không thể reload sơ đồ ghế vì Gui_BanVe chưa mở");
                System.out.println("💡 Vé đã lưu vào database. Khi mở lại màn hình bán vé, ghế sẽ hiển thị màu đỏ.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Số tiền không hợp lệ!",
                "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_QR dialog = new Dialog_QR(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // ========== GETTER METHODS ==========
    
    public boolean isNhapLai() {
        return isNhapLai;
    }
    
    public boolean isThanhToanThanhCong() {
        return isThanhToanThanhCong;
    }
    
    public boolean isTreoDon() {
        return isTreoDon;
    }
    
    public DonTreoDat getDonTreo() {
        return donTreo;
    }
    
    // ========== HELPER METHODS ==========
    
    /**
     * Tìm Gui_BanVe trong container (đệ quy)
     */
    private Gui_BanVe findGuiBanVe(Container container) {
        for (Component comp : container.getComponents()) {
            if (comp instanceof Gui_BanVe) {
                return (Gui_BanVe) comp;
            } else if (comp instanceof Container) {
                Gui_BanVe result = findGuiBanVe((Container) comp);
                if (result != null) {
                    return result;
                }
            }
        }
        return null;
    }
    
    /**
     * Tìm Gui_BanVe trong MainForm (dùng cho xử lý đơn treo)
     */
    private Gui_BanVe findGuiBanVeInMainForm(gui.menu.form.MainForm mainForm) {
        try {
            // MainForm thường có cấu trúc: MainForm -> Body (JPanel) -> CurrentForm
            Component[] components = mainForm.getComponents();
            for (Component comp : components) {
                if (comp instanceof Container) {
                    Gui_BanVe result = findGuiBanVe((Container) comp);
                    if (result != null) {
                        return result;
                    }
                }
            }
        } catch (Exception e) {
            System.err.println("Lỗi khi tìm Gui_BanVe: " + e.getMessage());
        }
        return null;
    }
    
    /**
     * Lưu dữ liệu vào database
     * @return true nếu thành công
     */
    private boolean luuVaoDatabase(String maHoaDon, String cccd, String hoTen, String sdt, String email, 
                                     int soLuongVe, double tongTien, double khuyenMai) {
        try {
            // ===== 1. TẠO/LẤY KHÁCH HÀNG =====
            KhachHang_DAO khachHangDAO = new KhachHang_DAO();
            KhachHang kh = khachHangDAO.findByCCCD(cccd);
            
            if (kh == null) {
                // Tạo khách hàng mới
                kh = new KhachHang();
                kh.setMaKH("KH" + System.currentTimeMillis());
                kh.setCCCD(cccd);
                kh.setHoTen(hoTen);
                kh.setSDT(sdt);
                kh.setEmail(email);
                kh.setDoiTuong(null);
                
                if (!khachHangDAO.them(kh)) {
                    System.out.println("Lỗi: Không thể tạo khách hàng!");
                    return false;
                }
            }
            
            // ===== 2. TẠO HÓA ĐƠN =====
            HoaDon hoaDon = new HoaDon();
            hoaDon.setMaHoaDon(maHoaDon);
            
            // Lấy nhân viên từ session
            NhanVien nv = new NhanVien();
            nv.setMaNhanVien(SessionManager.getInstance().getMaNhanVienDangNhap());
            hoaDon.setNhanVien(nv);
            
            hoaDon.setKhachHang(kh);
            hoaDon.setNgayTao(LocalDateTime.now());
            hoaDon.setGioTao(LocalDateTime.now());
            hoaDon.setTongTien(tongTien - khuyenMai);
            hoaDon.setTrangThai(true);
            
            HoaDon_DAO hoaDonDAO = new HoaDon_DAO();
            if (!hoaDonDAO.insertHoaDon(hoaDon)) {
                System.out.println("Lỗi: Không thể tạo hóa đơn!");
                return false;
            }
            
            // ===== 3. LƯU VÉ VÀ CHI TIẾT HÓA ĐƠN =====
            Ve_DAO veDAO = new Ve_DAO();
            ChiTietHoaDon_DAO chiTietDAO = new ChiTietHoaDon_DAO();
            LoaiVe_DAO loaiVeDAO = new LoaiVe_DAO();
            
            // Lấy danh sách vé từ donTreo
            if (donTreo != null) {
                List<DonTreoDat.ThongTinVeTam> danhSachVe = donTreo.getDanhSachVe();
                System.out.println("💳 ========== THANH TOÁN ĐƠN TREO ==========");
                System.out.println("💳 Số vé trong đơn: " + danhSachVe.size());
                
                for (int i = 0; i < danhSachVe.size(); i++) {
                    DonTreoDat.ThongTinVeTam veTam = danhSachVe.get(i);
                    
                    // Lấy LoaiVe
                    LoaiVe loaiVe = loaiVeDAO.findByTenLoaiVe(veTam.getDoiTuong());
                    
                    if (loaiVe == null) {
                        System.out.println("❌ LỖI: Không tìm thấy loại vé '" + veTam.getDoiTuong() + "' trong database!");
                        return false;
                    }
                    
                    // Lấy lịch trình từ vé tạm
                    LichTrinh lichTrinhCuaVe = veTam.getLichTrinh();
                    if (lichTrinhCuaVe == null) {
                        System.out.println("❌ LỖI: Vé #" + i + " không có lịch trình!");
                        return false;
                    }
                    
                    // ⚡ Nạp lại LichTrinh từ DB để tránh lỗi "no session"
                    LichTrinh_DAO ltDAO = new LichTrinh_DAO();
                    lichTrinhCuaVe = ltDAO.findByMaLichTrinh(lichTrinhCuaVe.getMaLichTrinh());
                    
                    // Tạo Vé
                    Ve ve = new Ve();
                    String maVe = "V" + System.currentTimeMillis() + "_" + i;
                    ve.setMaVe(maVe);
                    ve.setLoaiVe(loaiVe);
                    ve.setMaVach(null);
                    ve.setThoiGianLenTau(lichTrinhCuaVe != null ? lichTrinhCuaVe.getGioKhoiHanh() : null);
                    ve.setGiaVe(veTam.getGiaVe());
                    ve.setKhachHang(kh);
                    ve.setChoNgoi(veTam.getChoNgoi());
                    ve.setLichTrinh(lichTrinhCuaVe);
                    ve.setTrangThai(true);
                    ve.setTenKhachHang(veTam.getHoTen());
                    ve.setSoCCCD(veTam.getSoGiayTo());
                    
                    // ⚡ Bổ sung Ga đi / Ga đến
                    ve.setGaDi(veTam.getGaDi());
                    ve.setGaDen(veTam.getGaDen());
                    
                    if (!veDAO.insert(ve)) {
                        System.out.println("Lỗi: Không thể lưu vé từ đơn treo");
                        return false;
                    }
                    
                    // Tạo ChiTietHoaDon
                    ChiTietHoaDon cthd = new ChiTietHoaDon();
                    cthd.setHoaDon(hoaDon);
                    cthd.setVe(ve);
                    cthd.setSoLuong(1);
                    cthd.setGiaVe(veTam.getGiaVe());
                    cthd.setMucGiam(veTam.getGiamGia());
                    
                    if (!chiTietDAO.insert(cthd)) {
                        System.out.println("Lỗi: Không thể lưu chi tiết hóa đơn từ đơn treo");
                        return false;
                    }
                }
            }
            
            System.out.println("✅ Lưu database thành công! Mã hóa đơn: " + maHoaDon);
            return true;
            
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("❌ LỖI: " + e.getMessage());
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnQuayLai;
    private JButton btnThanhToan;
    private JButton btnTreoDon;
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel16;
    private JLabel jLabel2;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JLabel lblTien;
    private JPanel pnlQR;
    // End of variables declaration//GEN-END:variables
}
