package gui;

import connectDB.connectDB;
import entity.NhanVien;
import entity.TaiKhoan;
import service.ITaiKhoanService;
import utils.ClientContext;
import utils.SessionManager;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author PC
 */
public class Gui_Login extends JPanel {

    private ITaiKhoanService taiKhoanService;

    // Biến để theo dõi trạng thái hiện/ẩn mật khẩu
    private boolean isPasswordVisible = false;

    /**
     * Creates new form Gui_Login
     */
    public Gui_Login() {
        initComponents();
        taiKhoanService = ClientContext.getTaiKhoanService();

        txtTaiKhoan.setText("admin");
        txtMatKhau.setText("123456");

        // --- 1. CẤU HÌNH MẬT KHẨU ---
        // Mặc định ẩn mật khẩu bằng dấu *
        txtMatKhau.setEchoChar('*');

        // Thêm icon trỏ chuột dạng bàn tay cho icon mắt
        lblMK.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        // Xử lý sự kiện click vào icon mắt
        lblMK.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (isPasswordVisible) {
                    // Nếu đang hiện -> Ẩn đi
                    txtMatKhau.setEchoChar('*');
                    isPasswordVisible = false;
                    // (Tuỳ chọn) Bạn có thể đổi icon mắt đóng tại đây nếu có hình
                } else {
                    // Nếu đang ẩn -> Hiện ra (char 0 là ký tự rỗng)
                    txtMatKhau.setEchoChar((char) 0);
                    isPasswordVisible = true;
                    // (Tuỳ chọn) Bạn có thể đổi icon mắt mở tại đây
                }
            }
        });

        // --- 2. CẤU HÌNH NÚT THOÁT ---
        lblOut.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblOut.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        txtTaiKhoan = new JTextField();
        // SỬA: Đổi thành JPasswordField
        txtMatKhau = new JPasswordField();
        lblTaiKhoan = new JLabel();
        lblMatKhau = new JLabel();
        lbtTL = new JLabel();
        lblMK = new JLabel();
        btnDangNhap = new JButton();
        lblOut = new JLabel();

        jLabel1.setBackground(new Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/icon/train3.png"))); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        lblTaiKhoan.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblTaiKhoan.setText("Tài Khoản");

        lblMatKhau.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lblMatKhau.setText("Mật Khẩu");

        lbtTL.setIcon(new ImageIcon(getClass().getResource("/icon/userIcon.png"))); // NOI18N

        lblMK.setIcon(new ImageIcon(getClass().getResource("/icon/showIcon.png"))); // NOI18N

        btnDangNhap.setBackground(new Color(234, 243, 251));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        lblOut.setIcon(new ImageIcon(getClass().getResource("/icon/closeLoginIcon.png"))); // NOI18N

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblTaiKhoan, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblMatKhau)
                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtTaiKhoan, GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtMatKhau, GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(0, 33, Short.MAX_VALUE)
                                                                .addComponent(btnDangNhap)
                                                                .addGap(24, 24, 24)))
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(lbtTL))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblMK)))
                                                .addGap(25, 25, 25))))
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOut)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblOut)
                                .addGap(40, 40, 40)
                                .addComponent(lblTaiKhoan)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(lblMatKhau))
                                        .addComponent(txtTaiKhoan, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbtTL))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMK)
                                        .addComponent(txtMatKhau, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnDangNhap, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {
        // Khi nhấn Enter ở ô mật khẩu, tự động đăng nhập
        btnDangNhapActionPerformed(evt);
    }

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {
        String tenTaiKhoan = txtTaiKhoan.getText().trim();
        // Lấy mật khẩu từ JPasswordField (trả về mảng char, cần đổi sang String)
        String matKhau = new String(txtMatKhau.getPassword());

        // 1. Kiểm tra mật khẩu rỗng riêng biệt theo yêu cầu
        if (matKhau.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền mật khẩu!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            txtMatKhau.requestFocus();
            return;
        }

        // 2. Validate tài khoản rỗng
        if (tenTaiKhoan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền tên tài khoản!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            txtTaiKhoan.requestFocus();
            return;
        }

        // 3. Skip local DB check (handled by RMI)
        
        // 4. Thực hiện đăng nhập qua RMI
        try {
            TaiKhoan tk = taiKhoanService.dangNhap(tenTaiKhoan, matKhau);

            if (tk != null) {
                // Lấy trực tiếp NhanVien từ TaiKhoan (đã được Hibernate nạp)
                NhanVien nv = tk.getNhanVien();

                if (nv != null) {
                    // --- QUAN TRỌNG: Lưu vào Session ---
                    SessionManager.getInstance().setNhanVienDangNhap(nv);

                    // Mở màn hình chính
                    openMainFrame();
                } else {
                    JOptionPane.showMessageDialog(this, "Tài khoản không liên kết với nhân viên nào!", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sai tên tài khoản hoặc mật khẩu!", "Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
                txtMatKhau.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối Server: " + e.getMessage());
        }
    }

    private void openMainFrame() {
        // Lấy cửa sổ Login hiện tại để đóng sau này
        Window loginWindow = SwingUtilities.getWindowAncestor(this);

        SwingUtilities.invokeLater(() -> {
            try {
                // Khởi tạo màn hình chính
                // Giả sử class Main của bạn nằm trong package demo
                demo.Main mainFrame = new demo.Main();
                mainFrame.setVisible(true);

                // Đóng màn hình đăng nhập
                if (loginWindow != null) {
                    loginWindow.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi khởi tạo màn hình chính: " + e.getMessage());
            }
        });
    }

    // Variables declaration - do not modify
    private JButton btnDangNhap;
    private JLabel jLabel1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JLabel lblMK;
    private JLabel lblMatKhau;
    private JLabel lblOut;
    private JLabel lblTaiKhoan;
    private JLabel lbtTL;
    // SỬA: Đổi biến này thành JPasswordField
    private JPasswordField txtMatKhau;
    private JTextField txtTaiKhoan;
    // End of variables declaration
}